Repository beyondcode/laravel-websockets, pull requests merged in 2020-08, with the labels that each got.

#115 Add support for overriding stats logger's base URL
  config/websockets.php
  src/Statistics/Logger/HttpStatisticsLogger.php
Labels: question

#434 Fix 404 url by adding Request getBasePath
  resources/views/dashboard.blade.php
Labels: question

#284 [feature] Add restart command for WebSocket server
  src/Console/RestartWebSocketServer.php
  src/Console/StartWebSocketServer.php
  src/WebSocketsServiceProvider.php
  tests/Commands/RestartWebSocketServerTest.php
Labels: postponed

#140 Redis as a replication backend for scalability
  .gitignore
  composer.json
  config/websockets.php
  src/Apps/ConfigAppProvider.php
  src/Console/StartWebSocketServer.php
  src/Facades/StatisticsLogger.php
  src/Facades/WebSocketsRouter.php
  src/HttpApi/Controllers/Controller.php
  src/HttpApi/Controllers/FetchChannelController.php
  src/HttpApi/Controllers/FetchChannelsController.php
  src/HttpApi/Controllers/FetchUsersController.php
  src/HttpApi/Controllers/TriggerEventController.php
  src/PubSub/Broadcasters/RedisPusherBroadcaster.php
  src/PubSub/Drivers/LocalClient.php
  src/PubSub/Drivers/RedisClient.php
  src/PubSub/ReplicationInterface.php
  src/Server/Router.php
  src/WebSockets/Channels/Channel.php
  src/WebSockets/Channels/ChannelManagers/ArrayChannelManager.php
  src/WebSockets/Channels/PresenceChannel.php
  src/WebSockets/Channels/PrivateChannel.php
  src/WebSocketsServiceProvider.php
  tests/Channels/ChannelReplicationTest.php
  tests/Channels/ChannelTest.php
  tests/Channels/PresenceChannelReplicationTest.php
  tests/Channels/PresenceChannelTest.php
  tests/ClientProviders/AppTest.php
  tests/ConnectionTest.php
  tests/HttpApi/FetchChannelReplicationTest.php
  tests/HttpApi/FetchChannelTest.php
  tests/HttpApi/FetchChannelsReplicationTest.php
  tests/HttpApi/FetchUsersReplicationTest.php
  tests/Statistics/Controllers/WebSocketsStatisticsControllerTest.php
  tests/TestCase.php
  tests/TestsReplication.php
Labels: enhancement, help wanted

#414 Fix multiple routes not working when Logger enabled beyondcode#412
  src/Server/Logger/WebsocketsLogger.php
Labels: bug
